=== viktoria-kovacs/MentionPair/resources/sample/mmax/words.dtd
<!ELEMENT words (word*|sentence*)>
<!ELEMENT word (#PCDATA)>
<!ATTLIST word id ID #REQUIRED>
<!ELEMENT sentence (word*|sentence*)>
<!ATTLIST sentence id ID #REQUIRED>

=== viktoria-kovacs/MentionPair/resources/sample/mmax/Dem_def1.txt.conv.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE words SYSTEM "words.dtd">
<words>
<word id="word_1">﻿A</word>
<word id="word_2">﻿lány</word>
<word id="word_3">﻿egy</word>
<word id="word_4">﻿nyulat</word>
<word id="word_5">﻿kergetett</word>
<word id="word_6">﻿,</word>
<word id="word_7">﻿de</word>
<word id="word_8">﻿sehogyan</word>
<word id="word_9">﻿sem</word>
<word id="word_10">﻿tudta</word>
<word id="word_11">﻿elkapni</word>
<word id="word_12">﻿azt</word>
<word id="word_13">﻿.</word>
</words>
